(function () {

  var T = {
    pt: {
      /* ── Nav ── */
      'nav.about':        'Sobre',
      'nav.exp':          'Experiência',
      'nav.exp.levva':    'levva @ B3',
      'nav.exp.bot':      'Grupo Boticário',
      'nav.exp.ifood':    'iFood',
      'nav.exp.early':    'Engenharia & Pesquisa',
      'nav.projects':     'Projetos',
      'nav.testimonials': 'Depoimentos',
      'nav.edu':          'Formação',
      'nav.faq':          'FAQ',
      'nav.contact':      'Contato',

      /* ── Hero ── */
      'hero.tagline': 'Construo produtos digitais escaláveis unindo <strong>visão de negócio</strong> e <strong>base técnica</strong>. Guiada por dados, autonomia e muito trabalho em equipe.',
      'hero.intent':  'Sempre aberta a boas conversas.',
      'hero.stat.years':   'Anos como PM',
      'hero.stat.users':   'Usuários impactados',
      'hero.stat.current': 'Atual',
      'hero.cta.exp':      'Ver experiências',

      /* ── About ── */
      'about.label': 'Descrição',
      'about.title': 'Sobre mim',
      'about.p1': 'Comecei a carreira como engenheira de software. A transição para produto foi intencional: sempre fui muito curiosa, <strong>early bird de tecnologia e novos produtos</strong>, e alguém que gosta do desafio de entrar em setores novos do zero. A engenharia me dava o técnico, mas queria o todo. Quando descobri que PM era exatamente isso, não havia dúvida.',
      'about.p2': 'O que eu trago de diferente é <strong>empatia real com todas as áreas</strong>: engenharia, negócio, operações, stakeholders. Não finjo entender, ouço até entender de verdade. Nesses cinco anos passei por marketplaces com 350 mil usuários, varejo de beleza e mercado financeiro. E sou mão na massa: se não conheço algo, aprendo. No momento isso significa usar IA de verdade no meu próprio trabalho: em discoveries, na prototipação e na colaboração com design e dados. Só recomendo quando sei o que estou indicando.',
      'about.p3': 'Sou do Rio, casada com o Caio, e tenho dois cachorros: um salsicha e uma vira-lata. Fora do trabalho, provavelmente estou lendo um thriller, assistindo uma sitcom ou tomando café.',

      /* ── Experience ── */
      'exp.label':    'Trajetória',
      'exp.title':    'Experiências',
      'exp.subtitle': 'Clique em um card para ver mais detalhes.',
      'exp.cta':      'Ver detalhes',

      'exp.levva.role':   'Product Manager Senior',
      'exp.levva.period': 'Abril de 2026 – Presente',
      'exp.levva.hook':   'Estratégia de canais digitais no maior mercado financeiro da América Latina, em ambiente altamente regulado.',
      'exp.levva.hi1':    'PM consultora na B3 — Bolsa de Valores do Brasil',
      'exp.levva.hi2':    'Estratégia de Canais Digitais em ambiente altamente regulado',
      'exp.levva.hi3':    'Discovery e alinhamento com stakeholders de negócio, tech e ops',
      'exp.levva.tag1': 'Consultoria', 'exp.levva.tag2': 'Canais Digitais', 'exp.levva.tag3': 'Discovery', 'exp.levva.tag4': 'Ambiente Regulado', 'exp.levva.tag5': 'Stakeholders',

      'exp.bot.role':   'Product Manager Especialista',
      'exp.bot.period': 'Setembro de 2024 – Abril de 2026 · 1 ano 8 meses',
      'exp.bot.hook':   'Quando prever errado significa produto faltando na prateleira — discovery em ambiente de alto risco.',
      'exp.bot.hi1':    'Previsão de Sellout e Gestão de Demandas',
      'exp.bot.hi2':    'Novos Canais B2B — discovery e definição de MVP',
      'exp.bot.hi3':    'Mapeamento de jornadas e alinhamento técnico/operacional',
      'exp.bot.tag1': 'Indústria', 'exp.bot.tag2': 'Discovery', 'exp.bot.tag3': 'B2B', 'exp.bot.tag4': 'Previsão de Demanda', 'exp.bot.tag5': 'Alto Risco',

      'exp.ifood.period': 'Janeiro de 2020 – Maio de 2024 · 4 anos 5 meses',
      'exp.ifood.hook':   'De engenheira a PM Senior — 4 anos, 6 squads e 350 mil restaurantes.',
      'exp.ifood.hi1':    'CSAT do Portal de Parceiros: de 52 → 79 em 5 meses',
      'exp.ifood.hi2':    'Checkout e conversão do iFood Shop',
      'exp.ifood.hi3':    'Marketplace B2B para +350 mil restaurantes',
      'exp.ifood.tag1': 'Scale-up', 'exp.ifood.tag2': 'Marketplace', 'exp.ifood.tag3': 'B2B', 'exp.ifood.tag4': 'Conversão', 'exp.ifood.tag5': 'CSAT',

      'exp.early.role':   'Desenvolvedora · Pesquisadora',
      'exp.early.period': '2015 – 2020 · 5 anos',
      'exp.early.hook':   'Antes do produto, o código: como a engenharia moldou tudo que veio depois.',
      'exp.early.hi1':    '+250 mil estudantes impactados com o Trilha do Enem (Cogna)',
      'exp.early.hi2':    'Pesquisa em redes neurais para reconhecimento de imagens (CNPq)',
      'exp.early.tag1': 'Edtech', 'exp.early.tag2': 'Eng. de Software', 'exp.early.tag3': 'Pesquisa', 'exp.early.tag4': 'Dados',

      /* ── Testimonials ── */
      /* ── Personal projects ── */
      'proj.label':    'Projetos',
      'proj.title':    'Projetos pessoais',
      'proj.subtitle': 'Coisas que construí por iniciativa própria — com IA, curiosidade e vontade de resolver problemas reais.',
      'proj.deufit.desc': 'Plataforma que gera match entre candidato e vaga — com score de compatibilidade, dicas de negociação de salário e dados de layoff.',
      'proj.fresh.desc':  'Newsletter de carreira em tech — minhas experiências, aprendizados e perspectivas de quem está dentro do mercado.',
      'proj.pill.vibecoded': 'Vibe-coded',
      'proj.pill.ai':        'IA aplicada',
      'proj.pill.newsletter':'Newsletter',
      'proj.pill.career':    'Carreira em tech',

      'testimonials.label': 'Depoimentos',
      'testimonials.title': 'Quem trabalhou junto',

      /* ── Education ── */
      'edu.label':    'Formação',
      'edu.title':    'Educação & Certificações',
      'edu.academic': 'Formação Acadêmica',
      'edu.certs':    'Certificações',
      'edu.deg1':     'Bacharelado em Engenharia Mecânica',
      'edu.deg2':     'Intercâmbio · Engenharia Mecânica · Itália',
      'edu.deg3':     'Técnico em Informática',

      /* ── FAQ ── */
      'faq.label': 'Dúvidas frequentes',
      'faq.q1': 'Você está aberta a novas oportunidades?',
      'faq.a1': 'Sempre aberta a boas conversas. Se você está construindo algo interessante e acha que posso contribuir, me chama. Adoro trocar ideias sobre produto, mesmo que o timing não seja o ideal.',
      'faq.tag1': 'Oportunidades',
      'faq.q2': 'Como você usa IA no seu trabalho?',
      'faq.a2': 'IA já faz parte do meu dia a dia. Uso para tarefas operacionais como user stories, PRDs e documentações com agentes automatizados; para acelerar discoveries com benchmarks e compilados de dados; e para prototipação, incluindo código. Esse portfólio e o deufit.com foram construídos com IA. Gosto de testar novas ferramentas e acompanho esse espaço de perto.',
      'faq.tag2': 'Ferramentas',
      'faq.q3': 'Você atua em setores específicos?',
      'faq.a3': 'Não. Já trabalhei em marketplace, fintech, B2B, varejo e mercado financeiro. Recebo frequentemente o feedback de que tenho curva de aprendizado rápida e consigo entrar em novos negócios com agilidade. O que me importa é o problema a resolver, não o setor.',
      'faq.tag3': 'Setor',
      'faq.q4': 'O que você busca em uma posição?',
      'faq.a4': 'Autonomia para fazer discovery de verdade — entender o problema antes de construir. Gosto de trabalhar próxima a design, dados e engenharia, com voz na estratégia, não só na entrega. Não me identifico com papéis de PO operacionais onde o espaço é só de gestão de backlog.',
      'faq.tag4': 'Fit',
      'faq.q5': 'Qual modelo de trabalho você prefere?',
      'faq.a5': 'Remoto ou híbrido. Estou baseada no Rio de Janeiro e prefiro oportunidades que funcionem nesse modelo.',
      'faq.tag5': 'Modelo',
      'faq.q6': 'Como faço para entrar em contato?',
      'faq.a6': 'Pelo <a href="https://www.linkedin.com/in/camila-a-gomes/" target="_blank" rel="noopener">LinkedIn</a> é o melhor caminho. Me manda uma mensagem contando um pouco sobre o contexto e o que você está construindo.',
      'faq.tag6': 'Contato',

      /* ── Footer ── */
      'footer.tagline': 'Senior Product Manager · Brasil',

      /* ── Testimonials content ── */
      't1.role': 'PM Especialista',
      't1.text': '"Trabalhar com a Camila é ter a certeza de que desafios complexos serão resolvidos com maestria. O que mais admiro é como ela navega com naturalidade entre Engenharia, Negócios e Stakeholders, sempre falando a língua de cada público. Ela usa IA de forma estratégica para acelerar discussões e destravar alinhamentos em tempo recorde."',
      't2.text': '"Aprendi muito com sua dedicação, conhecimento técnico e senso crítico."',
      't3.text': '"Em todos os projetos pude constatar a sede em resolver problemas e a facilidade em criar conexões. Sorte de quem te tiver no time."',

      /* ── Common (sub-pages) ── */
      'common.back':   '← Voltar para experiências',
      'common.result': 'Resultado',

      /* ── levva ── */
      'levva.s1.m1.val': 'fragmentado',
      'levva.s1.m2.val': 'hero',
      'levva.s1.m3.val': 'marca',
      'levva.title':  'Product Manager Senior',
      'levva.period': 'Abril de 2026 – Presente · Posição atual',
      'levva.nav.context': 'Contexto',
      'levva.nav.results': 'Resultados',
      'levva.s1.chip':  'O Produto · Em andamento',
      'levva.s1.title': 'Hub PF — Porta de entrada<br>para o investidor',
      'levva.s1.body':  'Os canais digitais da B3 para a pessoa física estavam espalhados em múltiplos endereços, sem uma jornada coesa entre eles. O investidor chegava, não encontrava o que precisava, e saía. <strong>O Hub PF é a nova porta de entrada unificada</strong> — um ponto central onde a pessoa física encontra, navega e acessa os produtos e serviços da B3.',
      'levva.s1.problem.label': 'O problema',
      'levva.s1.m1.label': 'canais da B3 em<br>múltiplos domínios',
      'levva.s1.m2.label': 'única área com engajamento<br>na página antiga',
      'levva.s1.m3.label': 'posicionamento da B3<br>não reforçado digitalmente',
      'levva.s2.chip':  'Estratégia · Releases',
      'levva.s2.title': 'Projeto em fases,<br>entrega contínua',
      'levva.s2.body':  'O projeto foi quebrado em releases para viabilizar a entrega em um ambiente de alta complexidade regulatória e com múltiplos stakeholders. Cada release tem escopo definido, alinhamento com diretores e superintendentes, e entra em produção de forma independente.',
      'levva.r1.status': 'Concluído',
      'levva.r1.title': 'Release 1 — Nova Home',
      'levva.r1.desc':  'Página inicial do Hub PF no ar em <a href="https://www.investidor.b3.com.br" target="_blank" rel="noopener" style="color:#002c63; text-decoration:underline;">investidor.b3.com.br</a>. Estrutura visual unificada, navegabilidade melhorada e base para as próximas jornadas.',
      'levva.r2.status': 'Em andamento',
      'levva.r2.title': 'Release 2 — Jornada de Investimentos',
      'levva.r2.desc':  'Experiência educacional e acessível para o investidor pessoa física encontrar e entender os produtos de investimento da B3. Foco em clareza, descoberta e acessibilidade.',
      'levva.r3.status': 'Planejado',
      'levva.r3.title': 'Release 3 — Novos perfis',
      'levva.r3.desc':  'Expansão do modelo Hub para outros perfis e personas — novos jobs to be done mapeados e experiências dedicadas a cada tipo de investidor.',
      'levva.s3.chip':  'Contexto · Consultoria na B3',
      'levva.s3.title': 'PM em ambiente<br>de alta complexidade',
      'levva.s3.body':  'Atuar na B3 como consultora pela <strong>levva</strong> significa navegar um ambiente onde toda decisão passa por rodadas de aprovação com diretores e superintendentes, o compliance é inegociável e os sistemas legados têm alta criticidade. A velocidade de execução é equilibrada com rigor de governança.',
      'levva.jt1.label': 'Discovery & definição',
      'levva.jt1.sub':   'Mapeamento de jornadas, definição de escopo e priorização de cada release',
      'levva.jt2.label': 'Stakeholders complexos',
      'levva.jt2.sub':   'Alinhamento com diretores e superintendentes em ciclos de aprovação estruturados',
      'levva.jt3.label': 'Governança & agilidade',
      'levva.jt3.sub':   'Equilibrar velocidade de entrega com compliance e rigor de um ambiente financeiro regulado',
      'levva.insight.label': 'O modelo levva',
      'levva.insight.text':  'A <strong>levva</strong> posiciona especialistas como consultores integrados ao cliente — integrados ao time do cliente, com autonomia de PM, mas com a perspectiva externa de quem já navegou contextos diferentes. Esse modelo exige adaptação rápida e comunicação precisa em ambientes que não foram desenhados para velocidade.',
      'levva.s4.chip':   'Resultados iniciais · Release 1',
      'levva.s4.title':  'Primeiros sinais<br>de engajamento',
      'levva.s4.body':   'Com a nova home no ar, os primeiros dados já mostram uma mudança clara de comportamento em relação à página anterior.',
      'levva.jt4.label': 'Scroll depth',
      'levva.jt4.sub':   'Usuários estão scrollando significativamente mais do que na página antiga',
      'levva.jt5.label': 'Interação com componentes',
      'levva.jt5.sub':   'Engajamento distribuído por toda a página — antes concentrado apenas no hero',
      'levva.jt6.label': 'Em construção',
      'levva.jt6.sub':   'Release 2 em desenvolvimento — resultados consolidados ao final do projeto',
      'levva.nav.next':  'Grupo Boticário →',

      /* ── iFood ── */
      'ifood.page.title':  'Product Manager Senior',
      'ifood.page.period': 'Janeiro de 2020 – Maio de 2024 · 4 anos 5 meses',
      'ifood.nav.portal':   'Portal do Parceiro',
      'ifood.nav.editing':  'Edição de Pedidos',
      'ifood.nav.logistics':'Logística',
      'ifood.nav.origin':   'Origem',
      'ifood.s1.chip':   'PM Senior · Portal do Parceiro · 2022',
      'ifood.s1.title':  'Portal do Parceiro:<br>Experiência de Performance',
      'ifood.s1.body1':  'O Portal do Parceiro é a plataforma B2B onde mais de <strong>350 mil restaurantes</strong> gerenciam seu negócio dentro do iFood. A tensão de fundo era clara: muitos donos sentiam que <strong>eram obrigados a estar no iFood</strong>, sem perceber o valor que a plataforma podia gerar para eles. Além disso, não tinham benchmark — não sabiam se estavam indo bem ou mal, nem o que fazer para mudar.',
      'ifood.s1.body2':  'A proposta do squad era transformar dados de performance em <strong>informação clara, acionável e gratuita</strong> — reforçando a percepção de parceria, não de dependência.',
      'ifood.s1.disc.label': 'Como chegamos à solução',
      'ifood.jt1.label': 'Imersão diária com stakeholders',
      'ifood.jt1.sub':   'Contato quase diário com as áreas de negócio para entender expectativas e o que o produto precisava ser para eles',
      'ifood.jt2.label': 'Pesquisa quali e quanti com restaurantes',
      'ifood.jt2.sub':   'Entrevistas individuais e dinâmicas em grupo no fórum de parceiros para entender o que travava a compreensão dos dados',
      'ifood.jt3.label': 'Viabilidade com o time de dados',
      'ifood.jt3.sub':   'Alinhamento contínuo com analytics para mapear quais dados existiam, o que era confiável e o que era possível disponibilizar',
      'ifood.s1.built.label': 'O que foi construído',
      'ifood.f1.title': 'Painel de métricas',       'ifood.f1.desc': 'Vendas, pedidos e ticket médio em um só lugar',
      'ifood.f2.title': 'Benchmark com similares',   'ifood.f2.desc': 'Comparativo com restaurantes da mesma categoria e região',
      'ifood.f3.title': 'Recomendações de ação',     'ifood.f3.desc': 'O que fazer concretamente para melhorar a performance',
      'ifood.f4.title': 'Mapa de clientes',          'ifood.f4.desc': 'Onde estão geograficamente os clientes do restaurante',
      'ifood.f5.title': 'Itens mais vendidos',        'ifood.f5.desc': 'Quais pratos vendem mais e em que dias da semana',
      'ifood.f6.title': 'Tooltips explicativos',      'ifood.f6.desc': 'Linguagem acessível para donos com menor maturidade de dados',
      'ifood.s1.insight.label': 'A descoberta central',
      'ifood.s1.insight.text':  'O maior obstáculo não era falta de dados — era <strong>linguagem</strong>. Os donos de restaurante não entendiam os termos técnicos. Trocar o jargão por palavras do dia a dia, contextualizar os números com benchmarks e adicionar tooltips explicativos foi o que virou a agulha do CSAT.',
      'ifood.csat.title': 'CSAT em 5 meses',
      'ifood.csat.desc':  'Pesquisa qualitativa, ciclos curtos de iteração e linguagem acessível como alavanca principal.',
      'ifood.quote.body':   'Um restaurante no modelo <strong>dark kitchen</strong> relatou que, ao ver o mapa de localização dos seus clientes pela primeira vez, percebeu que podia mudar de endereço e economizar significativamente em frete — uma decisão estratégica que os dados tornaram possível.',
      'ifood.quote.source': 'Feedback qualitativo recebido após o lançamento do mapa de clientes',
      'ifood.s2.chip':  'O produto',
      'ifood.s2.body':  'O <strong>iFood Shop</strong> é o marketplace B2B do iFood — uma plataforma onde restaurantes compram insumos, embalagens e produtos de fornecedores diretamente pelo ecossistema do iFood. Durante quase 3 anos, passei pelas principais alavancas do produto: da logística até a refatoração completa do checkout.',
      'ifood.s2.link':  'Acessar iFood Shop →',
      'ifood.s3.chip':   'PM Senior · iFood Shop · 2022 – 2024',
      'ifood.s3.title':  'Refatoração do Carrinho & Checkout',
      'ifood.s3.body':   'O iFood Shop herdou o carrinho do app do iFood consumidor — que funciona bem para pedir uma pizza, mas não para o comportamento B2B. <strong>Restaurantes pesquisam, comparam preços entre fornecedores e montam o carrinho gradualmente.</strong> O funil mostrava que esse desalinhamento estava custando caro em conversão.',
      'ifood.s3.diag.label': 'O diagnóstico · antes da refatoração',
      'ifood.s3.m1.label': 'conversão no app<br><em style="font-style:normal;color:var(--muted-soft);">vs. 15% na web</em>',
      'ifood.s3.m2.label': 'abandono no carrinho<br>no app',
      'ifood.s3.m3.label': 'abandono no carrinho<br>na web',
      'ifood.s3.res.label': 'O que a pesquisa revelou',
      'ifood.jt4.label': 'Carrinho que esvaziava',
      'ifood.jt4.sub':   'Ao trocar de fornecedor, todos os itens sumiam — comportamento do app do consumidor que não faz sentido no B2B',
      'ifood.jt5.label': 'Bugs que travavam o fluxo',
      'ifood.jt5.sub':   'Teclado que subia e não fechava mais, bloqueando o usuário no meio da jornada',
      'ifood.jt6.label': 'Etapas na ordem errada',
      'ifood.jt6.sub':   'Pagamento vinha antes de entrega — mas o frete altera o valor final, forçando o usuário a voltar e revisar',
      'ifood.s3.built.label': 'O que foi construído',
      'ifood.g1.title': 'Carrinho multi-seller',       'ifood.g1.desc': 'Restaurantes adicionam itens de múltiplos fornecedores e fecham um pedido por vez',
      'ifood.g2.title': 'Fluxo invertido: entrega → pagamento', 'ifood.g2.desc': 'O usuário vê o valor final com frete antes de escolher o método de pagamento',
      'ifood.g3.title': 'Redesign do carrinho',         'ifood.g3.desc': 'Nova hierarquia visual, resumo claro do pedido e arquitetura de informação revisada',
      'ifood.g4.title': 'Correção de bugs e feedback',  'ifood.g4.desc': 'Eliminação dos erros que quebravam o fluxo e melhoria das mensagens de erro',
      'ifood.r1.delta': '↑ 9 pontos percentuais', 'ifood.r1.label': 'conversão no carrinho',
      'ifood.r2.delta': '↑ 12 pontos percentuais','ifood.r2.label': 'conversão total no app',
      'ifood.r3.delta': 'GMV 2,5×',               'ifood.r3.label': 'de 400 mil → 1 milhão em GMV',
      'ifood.s4.chip':  'PM Pleno · iFood Shop · 2022',
      'ifood.s4.title': 'Edição de Pedidos & Ruptura',
      'ifood.s4.body':  'No squad de Admin para Fornecedores, o foco era dar <strong>autonomia operacional aos fornecedores</strong> do Shop. Antes dessa funcionalidade, qualquer ajuste em um pedido — item em falta, quantidade errada ou cancelamento — exigia que o fornecedor contatasse o suporte do iFood, que então entrava em contato manualmente com o restaurante comprador.',
      'ifood.before.label': 'Antes da feature',
      'ifood.before.step1': 'Fornecedor detecta problema',
      'ifood.before.step2': 'Liga / envia e-mail ao suporte',
      'ifood.before.step3': 'Suporte contata o restaurante',
      'ifood.before.step4': 'Estorno manual',
      'ifood.before.note':  'Processo lento, dependente de terceiros e gerador de chamados.',
      'ifood.node1.tag':   'O que mudou',
      'ifood.node1.title': 'Fornecedor edita o pedido diretamente na plataforma',
      'ifood.node1.sub':   'Três tipos de edição disponíveis',
      'ifood.jt7.label': 'Ruptura total',         'ifood.jt7.sub': 'Item completamente indisponível no estoque',
      'ifood.jt8.label': 'Redução de quantidade', 'ifood.jt8.sub': 'Pediu 10, tem só 6 — ajuste parcial',
      'ifood.jt9.label': 'Cancelamento total',     'ifood.jt9.sub': 'Pedido inteiro indisponível para entrega',
      'ifood.node2.tag':   'Processamento automático',
      'ifood.node2.title': 'Sistema calcula e processa o estorno por método de pagamento',
      'ifood.node2.sub':   'Lógica específica para cada forma — sem intervenção manual',
      'ifood.pay1.method': 'Cartão de crédito',  'ifood.pay1.action': 'Novo pré-aprovado gerado na mesma sessão',
      'ifood.pay2.method': 'PIX',                'ifood.pay2.action': 'Estorno instantâneo para a chave de origem',
      'ifood.pay3.method': 'Boleto a prazo',      'ifood.pay3.action': 'Novo boleto emitido com valor ajustado',
      'ifood.out1': '<span class="material-symbols-outlined">notifications</span> <span>Restaurante notificado automaticamente</span>',
      'ifood.out2': '<span class="material-symbols-outlined">notifications_off</span> <span>Suporte fora do loop</span>',
      'ifood.out3': '<span class="material-symbols-outlined">trending_down</span> <span>Chamados de suporte reduzidos</span>',
      'ifood.s4.insight.text': 'O suporte saiu completamente do loop. Fornecedores passaram a resolver ocorrências de forma autônoma, o estorno foi automatizado por método de pagamento e os chamados relacionados a pedidos com problema caíram significativamente — sem nenhuma intervenção manual necessária.',
      'ifood.s5.chip':  'PM Júnior · iFood Shop · 2021 – 2022',
      'ifood.s5.title': 'Logística & Pós-venda',
      'ifood.s5.body':  'Minha primeira posição como PM foi no squad de pós-venda e logística do iFood Shop. O desafio central era <strong>expandir a base de fornecedores sem frota própria</strong> e melhorar a experiência de entrega de ponta a ponta. Três frentes principais:',
      'ifood.i1.title': 'Logística como Serviço (LaaS)', 'ifood.i1.desc': 'Integração de transportadoras terceiras ao ecossistema do Shop, abrindo portas para fornecedores sem frota própria. Solução escalável e replicável para o marketplace.',
      'ifood.i1.link': 'Ver publicação →',
      'ifood.i2.title': 'Agendamento de Entregas',       'ifood.i2.desc': 'Feature que permitia restaurantes planejarem recebimentos com antecedência — menos imprevistos na operação e mais controle sobre o fluxo de estoque.',
      'ifood.i3.title': 'Fluxo de Comunicação',          'ifood.i3.desc': 'Estruturação do fluxo de comunicação pós-compra via <strong>e-mail e WhatsApp</strong>, mantendo fornecedores e compradores alinhados ao longo de toda a jornada de entrega.',
      'ifood.s5.insight.text': 'A integração via LaaS abriu o marketplace para fornecedores sem frota própria, aumentando diretamente a base de parceiros disponíveis. O agendamento de entregas e o fluxo de comunicação pós-compra reduziram os atritos operacionais — melhorando a experiência de restaurantes e fornecedores ao longo de toda a jornada.',
      'ifood.s6.chip':  'Origem · 2020 – 2021',
      'ifood.s6.title': 'Onde tudo começou',
      'ifood.s6.body':  'Entrei no iFood como <strong>Engenheira de Software</strong> pelo programa <strong>Mobile Dream</strong> — iniciativa do iFood para contratar e desenvolver analistas júniors. Trabalhei no backend do Portal do Parceiro, no produto de Cardápio. Essa experiência foi o ponto de partida: entender profundamente como o produto funcionava por dentro me deu a base para a transição interna para Product Management.',
      'ifood.nav.prev': '← Grupo Boticário',
      'ifood.nav.next': 'Engenharia & Pesquisa →',

      /* ── Boticário ── */
      'bot.page.title':  'Product Manager Especialista',
      'bot.page.period': 'Setembro de 2024 – Abril de 2026 · 1 ano 8 meses',
      'bot.nav.sellout': 'Previsão Sellout',
      'bot.nav.results': 'Resultados',
      'bot.s1.chip':  'O Produto',
      'bot.s1.title': 'GDEM — Gestão de Demanda',
      'bot.s1.body':  'O GDEM é a ferramenta interna de planejamento de demanda do Grupo Boticário. Com modelos estatísticos, ela auxilia planejadores a prever a demanda dos SKUs — e essa previsão vai direto para o Supply para orientar a fabricação. Não há margem para erro: <strong>uma previsão errada significa ruptura nas prateleiras das franquias.</strong>',
      'bot.s1.problem.label': 'Contexto & escala',
      'bot.s1.m1.label': 'SKUs planejados — marcas<br>Boticário e Eudora',
      'bot.s1.m2.label': 'planejadores responsáveis<br>por todo esse volume',
      'bot.s1.m3.label': 'margem para erro — previsão<br>errada vai direto para o Supply',
      'bot.s1.did.label': 'O que fiz',
      'bot.jt1.label': 'Discovery de dores',   'bot.jt1.sub': 'Entrevistas com planejadores para entender o que travava o processo e onde o modelo falhava',
      'bot.jt2.label': 'Refinamento com dados', 'bot.jt2.sub': 'Backlog priorizado junto ao time de Ciência de Dados, com critérios claros de impacto e viabilidade',
      'bot.jt3.label': 'Métricas de sucesso',   'bot.jt3.sub': 'Definição de KPIs de acurácia (WAPE) e tempo de planejamento como norte para o squad',
      'bot.s2.chip':  'Frente 1 · Discovery B2B',
      'bot.s2.title': 'Expandindo o GDEM<br>para o canal B2B',
      'bot.s2.body':  'O GDEM foi construído para o processo padrão da empresa — mas o canal B2B opera com dinâmicas próprias que o produto não suportava. O time de B2B entendia que o GDEM simplesmente <strong>"não funcionava para eles"</strong>. O time do GDEM, por sua vez, não conhecia como o B2B operava. Sem esse entendimento mútuo, qualquer solução seria um tiro no escuro.',
      'bot.s2.areas.label': '5 áreas mapeadas no assessment',
      'bot.a1.title': 'Planejadores de Demanda B2B', 'bot.a1.desc': 'Usuários diretos do GDEM no canal B2B',
      'bot.a2.title': 'Gerentes de Demanda B2B',     'bot.a2.desc': 'Stakeholders com visão estratégica do canal',
      'bot.a3.title': 'Planejamento Comercial',       'bot.a3.desc': 'Área que conecta demanda às metas comerciais',
      'bot.a4.title': 'Torre de Controle',            'bot.a4.desc': 'Visão operacional e de monitoramento',
      'bot.a5.title': 'Dados',                       'bot.a5.desc': 'Time técnico responsável pelos modelos e infraestrutura',
      'bot.s2.insight1.label': 'A descoberta central',
      'bot.s2.insight1.text':  'O gap não era técnico — era conceitual. O B2B tinha um processo de demanda fundamentalmente diferente do canal padrão, e nenhum dos dois lados conhecia bem o outro. A principal entrega do assessment foi criar uma linguagem comum entre os dois mundos e, a partir daí, recortar um MVP viável.',
      'bot.s2.del.label': 'O que foi entregue',
      'bot.jt4.label': 'Mapeamento completo', 'bot.jt4.sub': 'Processo de demanda B2B documentado do início ao fim, com dados de viabilidade',
      'bot.jt5.label': 'Alinhamento de 5 áreas','bot.jt5.sub': 'Reviews quinzenais até todas as partes chegarem a um entendimento comum',
      'bot.jt6.label': 'MVP definido',           'bot.jt6.sub': 'Épicos e histórias quebrados, viabilidade mapeada — pronto para construção',
      'bot.s2.insight2.text': 'Após 10 entrevistas com stakeholders de 5 áreas e 4 reviews quinzenais, o discovery chegou a um MVP bem definido — e a diretoria aprovou o recorte para seguir com o desenvolvimento. A decisão posterior de despriorizar foi de negócio, não de falta de clareza: o produto estava pronto para ser construído, mas outras iniciativas tomaram precedência. <strong>Um discovery que gera uma decisão informada é um discovery bem feito.</strong>',
      'bot.s3.chip':  'Frente 2 · PM de Sellout',
      'bot.s3.title': 'Previsão de Vendas<br>para o Consumidor',
      'bot.s3.body':  'Como PM do squad de Previsão de Sellout, o maior problema ao entrar não era falta de feature — era uma <strong>avalanche de incidentes de dados incorretos</strong>. Para 15 planejadores com alta carga operacional, um dado errado significava subir uma previsão incorreta direto para o Supply. Não havia margem para erro.',
      'bot.s3.diag.label': 'O diagnóstico',
      'bot.s3.diag.text':  'Regras de negócio haviam sido mal alinhadas entre business e tech durante o desenvolvimento. O que estava codado divergia do que os stakeholders esperavam — os cálculos traziam resultados diferentes do previsto. Não era culpa de nenhuma área em específico, mas precisava ser corrigido.',
      'bot.s3.did.label': 'O que foi feito',
      'bot.jt7.label': 'Mapeamento regra por regra', 'bot.jt7.sub': 'Sentou com pessoas-chave da área de demanda e documentou cada lógica de cálculo — caso a caso, modelo a modelo',
      'bot.jt8.label': 'Validação com o código',     'bot.jt8.sub': 'Comparou o que estava implementado com o que foi mapeado, identificando onde os cálculos divergiam da expectativa',
      'bot.jt9.label': 'Priorização e visibilidade',  'bot.jt9.sub': 'Organizou as incongruências encontradas, priorizou os ajustes e deu visibilidade clara ao time de negócios',
      'bot.s3.result.label': 'Resultado',
      'bot.s3.stat.label': 'incidentes de dados',
      'bot.s3.stat.desc':  'O mapeamento sistemático das regras de negócio transformou um problema crônico de qualidade em um processo confiável de validação.',
      'bot.s3.decision.label': 'Uma decisão de prioridade',
      'bot.s3.decision.text':  'Durante a expansão para a marca Eudora — com data limite definida — o time de negócios trouxe com urgência um problema de performance em múltiplas agendas simultâneas e pediu para paralisar tudo. Em vez de ceder à pressão, sentei com as pessoas-chave e fiz as perguntas certas: <em>quantos incidentes foram abertos por isso? O que causou o problema? Faz sentido atrasar a expansão para resolver isso agora?</em> A resposta foi: nenhum incidente, causa pontual, cenário médio — não crítico. Juntos, chegamos à conclusão de que a expansão era a prioridade. O problema de performance foi resolvido logo depois.',
      'bot.s3.other.label': 'Outras responsabilidades do squad',
      'bot.h1.title': 'Assertividade (WAPE)',       'bot.h1.desc': 'Monitoramento contínuo da acurácia das previsões geradas pelo modelo de dados',
      'bot.h2.title': 'Experiência do planejador',  'bot.h2.desc': 'UX dentro do GDEM — o sistema passou a consolidar dados antes espalhados em múltiplas planilhas e bases',
      'bot.h3.title': 'Curva C simplificada',       'bot.h3.desc': 'Produtos de baixo impacto deixaram de passar pelo processo complexo — o volume do modelo estatístico passou a ser confiado diretamente',
      'bot.h4.title': 'Interface com Ciência de Dados','bot.h4.desc': 'Integração do modelo ao produto e validação dos outputs com o time de dados',
      'bot.s4.chip':  'Resultados · GDEM',
      'bot.s4.title': 'Impacto no planejamento<br>da companhia',
      'bot.r1.delta': '↓ 50% no ciclo', 'bot.r1.label': 'ciclo de planejamento<br><em style="font-style:normal;color:var(--muted-soft);">antes: 40 dias</em>',
      'bot.r2.delta': 'assertividade da previsão', 'bot.r2.label': 'acurácia das previsões<br>de demanda',
      'bot.r3.delta': '↓ incidentes de dados',     'bot.r3.label': 'redução de incidentes<br>no squad de Sellout',
      'bot.nav.prev': '← levva @ B3',
      'bot.nav.next': 'iFood →',

      /* ── Early Career ── */
      'early.page.title':  'Engenharia de Software & Pesquisa',
      'early.page.period': '2015 – 2020 · 5 anos · A base técnica que diferencia',
      'early.s1.title': 'Por que isso importa',
      'early.s1.intro': 'Antes de me tornar PM, fui engenheira de software. Essa trajetória não é apenas um detalhe de currículo — é o que me diferencia. Entendo o que os times de tecnologia enfrentam, consigo ler código, participar de decisões de arquitetura e comunicar requisitos com precisão. Essa base foi construída na <strong>Cogna Educação</strong> e no <strong>CNPq</strong>, antes de entrar para o iFood.',
      'early.s2.title': 'Cogna Educação · Plataforma de Provas · 2018 – Dez 2019',
      'early.provas.name': 'Plataforma de Provas',
      'early.provas.sub':  'Portal para professores criarem e gerirem avaliações digitais',
      'early.provas.ctx':  'Sistema interno voltado para <strong>professores</strong> do ecossistema Kroton / Cogna: um portal onde podiam cadastrar questões, montar provas e acompanhar o desempenho dos alunos por turma. Trabalhei no desenvolvimento e evolução da plataforma como Desenvolvedora, centralizando o fluxo de avaliação — da elaboração das questões até a aplicação digital.',
      'early.stack.label': 'Stack utilizada',
      'early.s3.title': 'Cogna Educação · Trilha do Enem · Jan 2017 – Dez 2017',
      'early.enem.name': 'Trilha do Enem',
      'early.enem.sub':  'Plataforma gratuita de preparação adaptativa para o ENEM',
      'early.enem.stat': 'estudantes impactados',
      'early.enem.link1': 'Como estudar para o ENEM de graça',
      'early.enem.link2': 'O que é e como funciona',
      'early.enem.link3': 'Canal oficial',
      'early.enem.ctx':  'Entrei na Cogna como estagiária e fui efetivada como Desenvolvedora. Trabalhei na construção e evolução do <strong>Trilha do Enem</strong>, uma plataforma gratuita que oferecia aulas, simulados e plano de estudos adaptativo para estudantes do Brasil inteiro. A plataforma foi coberta pela imprensa e chegou a mais de <strong>250 mil usuários</strong>.',
      'early.s4.title': 'AceleraDev Java Women · Codenation + QuintoAndar · 2019',
      'early.acelera.name': 'AceleraDev Java Women',
      'early.acelera.sub':  'Programa exclusivo para mulheres em Back-end Java',
      'early.acelera.stat': 'mulheres selecionadas<br>de quase 2 mil inscritas',
      'early.acelera.ctx':  'No fim de 2019, fui selecionada para o <strong>AceleraDev Java Women</strong> — um programa gratuito e exclusivo para mulheres, criado pela Codenation em parceria com o <strong>QuintoAndar</strong>. Foram 10 semanas de imersão em desenvolvimento Back-end com Java, com aulas presenciais na sede do QuintoAndar em São Paulo e desafios semanais de código. Das 30 participantes selecionadas, o QuintoAndar contratou 11 diretamente ao final do programa.',
      'early.s5.title': 'CNPq · Iniciação Científica · Dez 2015 – Dez 2016',
      'early.cnpq.name': 'FXCode — Reconhecimento de Ícones',
      'early.cnpq.sub':  'Pesquisa em redes neurais convolucionais aplicada a reconhecimento de imagens',
      'early.cnpq.stat': 'plataformas do app onde o modelo foi implementado',
      'early.cnpq.ctx':  'Bolsista do <strong>CNPq</strong>, realizei iniciação científica na área de reconhecimento de imagens utilizando <strong>redes neurais de convolução</strong>. No projeto <strong>FXCode</strong>, fui responsável por produzir um modelo capaz de reconhecer ícones — treinado em Python com a biblioteca Keras — e integrá-lo a um aplicativo mobile para Android e iOS.',
      'early.nav.prev': '← iFood',
      'early.nav.next': 'levva @ B3 →',
    },

    en: {
      /* ── Nav ── */
      'nav.about':        'About',
      'nav.exp':          'Experience',
      'nav.exp.levva':    'levva @ B3',
      'nav.exp.bot':      'Grupo Boticário',
      'nav.exp.ifood':    'iFood',
      'nav.exp.early':    'Engineering & Research',
      'nav.projects':     'Projects',
      'nav.testimonials': 'Testimonials',
      'nav.edu':          'Education',
      'nav.faq':          'FAQ',
      'nav.contact':      'Contact',

      /* ── Hero ── */
      'hero.tagline': 'I build scalable digital products that bridge <strong>business vision</strong> and <strong>technical depth</strong>. Driven by data, ownership, and teamwork.',
      'hero.intent':  'Don\'t be a stranger.',
      'hero.stat.years':   'Years as PM',
      'hero.stat.users':   'Users impacted',
      'hero.stat.current': 'Current',
      'hero.cta.exp':      'View experience',

      /* ── About ── */
      'about.label': 'About',
      'about.title': 'About me',
      'about.p1': 'I started my career as a software engineer. The move into product was intentional: I\'ve always been deeply curious, an <strong>early adopter of technology and new products</strong>, and someone who thrives on entering new domains from scratch. Engineering gave me the technical foundation, but I wanted the full picture. When I discovered PM was exactly that, there was no hesitation.',
      'about.p2': 'What I bring is <strong>genuine empathy across all areas</strong>: engineering, business, operations, and stakeholders. I don\'t pretend to understand — I listen until I actually do. Over five years I\'ve worked across a 350k-user marketplace, beauty retail, and financial markets. I\'m hands-on: if I don\'t know something, I learn it. Right now that means actually using AI in my own work — in discovery, prototyping, and collaboration with design and data. I only recommend what I\'ve tested myself.',
      'about.p3': 'I\'m from Rio de Janeiro, married to Caio, and we have two dogs — a dachshund and a mutt. Outside of work, I\'m probably reading a thriller, watching a sitcom, or drinking coffee.',

      /* ── Experience ── */
      'exp.label':    'Career',
      'exp.title':    'Experience',
      'exp.subtitle': 'Click on a card to see more details.',
      'exp.cta':      'See details',

      'exp.levva.role':   'Senior Product Manager',
      'exp.levva.period': 'April 2026 – Present',
      'exp.levva.hook':   'Digital channel strategy at Latin America\'s largest financial exchange, in a highly regulated environment.',
      'exp.levva.hi1':    'Consultant PM at B3 — Brazil\'s Stock Exchange',
      'exp.levva.hi2':    'Digital Channel Strategy in a highly regulated environment',
      'exp.levva.hi3':    'Discovery and alignment with business, tech, and ops stakeholders',
      'exp.levva.tag1': 'Consulting', 'exp.levva.tag2': 'Digital Channels', 'exp.levva.tag3': 'Discovery', 'exp.levva.tag4': 'Regulated Environment', 'exp.levva.tag5': 'Stakeholders',

      'exp.bot.role':   'Staff Product Manager',
      'exp.bot.period': 'September 2024 – April 2026 · 1 year 8 months',
      'exp.bot.hook':   'When a wrong forecast means empty shelves — discovery in a high-stakes environment.',
      'exp.bot.hi1':    'Sellout Forecasting and Demand Management',
      'exp.bot.hi2':    'New B2B Channels — discovery and MVP definition',
      'exp.bot.hi3':    'Journey mapping and technical/operational alignment',
      'exp.bot.tag1': 'Industry', 'exp.bot.tag2': 'Discovery', 'exp.bot.tag3': 'B2B', 'exp.bot.tag4': 'Demand Forecasting', 'exp.bot.tag5': 'High-Stakes',

      'exp.ifood.period': 'January 2020 – May 2024 · 4 years 5 months',
      'exp.ifood.hook':   'From engineer to Senior PM — 4 years, 6 squads, and 350k restaurants.',
      'exp.ifood.hi1':    'Partner Portal CSAT: from 52 → 79 in 5 months',
      'exp.ifood.hi2':    'iFood Shop checkout and conversion',
      'exp.ifood.hi3':    'B2B marketplace for +350k restaurants',
      'exp.ifood.tag1': 'Scale-up', 'exp.ifood.tag2': 'Marketplace', 'exp.ifood.tag3': 'B2B', 'exp.ifood.tag4': 'Conversion', 'exp.ifood.tag5': 'CSAT',

      'exp.early.role':   'Software Developer · Researcher',
      'exp.early.period': '2015 – 2020 · 5 years',
      'exp.early.hook':   'Before product, code: how engineering shaped everything that came after.',
      'exp.early.hi1':    '+250k students reached through Trilha do Enem (Cogna)',
      'exp.early.hi2':    'Neural network research for image recognition (CNPq)',
      'exp.early.tag1': 'Edtech', 'exp.early.tag2': 'Software Eng.', 'exp.early.tag3': 'Research', 'exp.early.tag4': 'Data',

      /* ── Personal projects ── */
      'proj.label':    'Projects',
      'proj.title':    'Personal projects',
      'proj.subtitle': 'Things I built on my own initiative — with AI, curiosity, and a drive to solve real problems.',
      'proj.deufit.desc': 'Platform that matches candidates to job openings — with a compatibility score, salary negotiation tips, and layoff data.',
      'proj.fresh.desc':  'Career newsletter in tech — my experiences, lessons learned, and perspectives from inside the industry.',
      'proj.pill.vibecoded': 'Vibe-coded',
      'proj.pill.ai':        'Applied AI',
      'proj.pill.newsletter':'Newsletter',
      'proj.pill.career':    'Tech careers',

      /* ── Testimonials ── */
      'testimonials.label': 'Testimonials',
      'testimonials.title': 'People who worked with me',

      /* ── Education ── */
      'edu.label':    'Education',
      'edu.title':    'Education & Certifications',
      'edu.academic': 'Academic Background',
      'edu.certs':    'Certifications',
      'edu.deg1':     'Bachelor\'s in Mechanical Engineering',
      'edu.deg2':     'Exchange Program · Mechanical Engineering · Italy',
      'edu.deg3':     'Technical Degree in Computer Science',

      /* ── FAQ ── */
      'faq.label': 'Common questions',
      'faq.q1': 'Are you open to new opportunities?',
      'faq.a1': 'Always open to great conversations. If you\'re building something interesting and think I could contribute, reach out. I love exchanging ideas about product, even if the timing isn\'t perfect.',
      'faq.tag1': 'Opportunities',
      'faq.q2': 'How do you use AI in your work?',
      'faq.a2': 'AI is already part of my daily workflow. I use it for operational tasks like user stories, PRDs, and documentation with automated agents; to speed up discovery with benchmarks and data analysis; and for prototyping, including code. This portfolio and deufit.com were built with AI. I enjoy testing new tools and closely follow this space.',
      'faq.tag2': 'Tools',
      'faq.q3': 'Do you focus on specific industries?',
      'faq.a3': 'No. I\'ve worked across marketplace, fintech, B2B, retail, and financial markets. I often receive feedback that I have a fast learning curve and can quickly ramp up in new domains. What matters to me is the problem to solve, not the sector.',
      'faq.tag3': 'Industry',
      'faq.q4': 'What are you looking for in a role?',
      'faq.a4': 'Autonomy to do real discovery — understanding the problem before building. I like working closely with design, data, and engineering, with a voice in strategy, not just delivery. I don\'t see myself in operational PO roles where the scope is limited to backlog management.',
      'faq.tag4': 'Fit',
      'faq.q5': 'What\'s your preferred work model?',
      'faq.a5': 'Remote or hybrid. I\'m based in Rio de Janeiro and prefer opportunities that work within that setup.',
      'faq.tag5': 'Model',
      'faq.q6': 'How can I get in touch?',
      'faq.a6': '<a href="https://www.linkedin.com/in/camila-a-gomes/" target="_blank" rel="noopener">LinkedIn</a> is the best way to reach me. Send a message with a bit of context about what you\'re building.',
      'faq.tag6': 'Contact',

      /* ── Footer ── */
      'footer.tagline': 'Senior Product Manager · Brazil',

      /* ── Testimonials content ── */
      't1.role': 'Staff Product Manager',
      't1.text': '"Working with Camila means knowing that complex challenges will be handled with mastery. What I admire most is how naturally she navigates between Engineering, Business, and Stakeholders, always speaking each audience\'s language. She uses AI strategically to accelerate discussions and unlock alignment in record time."',
      't2.text': '"I learned so much from her dedication, technical knowledge, and critical thinking."',
      't3.text': '"In every project, I witnessed the drive to solve problems and the ease in creating connections. Lucky is whoever has you on their team."',

      /* ── Common (sub-pages) ── */
      'common.back':   '← Back to experience',
      'common.result': 'Result',

      /* ── levva ── */
      'levva.s1.m1.val': 'fragmented',
      'levva.s1.m2.val': 'hero',
      'levva.s1.m3.val': 'brand',
      'levva.title':  'Senior Product Manager',
      'levva.period': 'April 2026 – Present · Current position',
      'levva.nav.context': 'Context',
      'levva.nav.results': 'Results',
      'levva.s1.chip':  'The Product · In progress',
      'levva.s1.title': 'Hub PF — The investor\'s<br>front door',
      'levva.s1.body':  'B3\'s digital channels for individual investors were scattered across multiple addresses, with no cohesive journey between them. Investors arrived, couldn\'t find what they needed, and left. <strong>Hub PF is the new unified entry point</strong> — a central hub where individuals discover, navigate, and access B3\'s products and services.',
      'levva.s1.problem.label': 'The problem',
      'levva.s1.m1.label': 'B3 channels across<br>multiple domains',
      'levva.s1.m2.label': 'only area with engagement<br>on the old page',
      'levva.s1.m3.label': 'B3\'s positioning not<br>reinforced digitally',
      'levva.s2.chip':  'Strategy · Releases',
      'levva.s2.title': 'Phased project,<br>continuous delivery',
      'levva.s2.body':  'The project was broken into releases to enable delivery in a high regulatory-complexity environment with multiple stakeholders. Each release has a defined scope, alignment with directors and superintendents, and ships to production independently.',
      'levva.r1.status': 'Done',
      'levva.r1.title': 'Release 1 — New Homepage',
      'levva.r1.desc':  'Hub PF homepage live at <a href="https://www.investidor.b3.com.br" target="_blank" rel="noopener" style="color:#002c63; text-decoration:underline;">investidor.b3.com.br</a>. Unified visual structure, improved navigation, and the foundation for upcoming journeys.',
      'levva.r2.status': 'In progress',
      'levva.r2.title': 'Release 2 — Investment Journey',
      'levva.r2.desc':  'Educational and accessible experience for individual investors to discover and understand B3\'s investment products. Focus on clarity, discovery, and accessibility.',
      'levva.r3.status': 'Planned',
      'levva.r3.title': 'Release 3 — New Profiles',
      'levva.r3.desc':  'Expanding the Hub model to other profiles and personas — new jobs-to-be-done mapped and dedicated experiences for each investor type.',
      'levva.s3.chip':  'Context · Consulting at B3',
      'levva.s3.title': 'PM in a high-complexity<br>environment',
      'levva.s3.body':  'Working at B3 as a consultant from <strong>levva</strong> means navigating an environment where every decision goes through rounds of approval with directors and superintendents, compliance is non-negotiable, and legacy systems have high criticality. Execution speed is balanced with governance rigor.',
      'levva.jt1.label': 'Discovery & definition',
      'levva.jt1.sub':   'Journey mapping, scope definition, and prioritization for each release',
      'levva.jt2.label': 'Complex stakeholders',
      'levva.jt2.sub':   'Alignment with directors and superintendents in structured approval cycles',
      'levva.jt3.label': 'Governance & agility',
      'levva.jt3.sub':   'Balancing delivery speed with compliance and the rigor of a regulated financial environment',
      'levva.insight.label': 'The levva model',
      'levva.insight.text':  '<strong>levva</strong> places specialists as embedded consultants — integrated into the client\'s team with PM autonomy, but with the external perspective of someone who has navigated different contexts. This model demands fast adaptation and precise communication in environments not built for speed.',
      'levva.s4.chip':   'Early results · Release 1',
      'levva.s4.title':  'First signs<br>of engagement',
      'levva.s4.body':   'With the new homepage live, early data already shows a clear shift in behavior compared to the previous page.',
      'levva.jt4.label': 'Scroll depth',
      'levva.jt4.sub':   'Users are scrolling significantly more than on the old page',
      'levva.jt5.label': 'Component interaction',
      'levva.jt5.sub':   'Engagement distributed across the full page — previously concentrated only in the hero',
      'levva.jt6.label': 'In progress',
      'levva.jt6.sub':   'Release 2 in development — consolidated results at project completion',
      'levva.nav.next':  'Grupo Boticário →',

      /* ── iFood ── */
      'ifood.page.title':  'Senior Product Manager',
      'ifood.page.period': 'January 2020 – May 2024 · 4 years 5 months',
      'ifood.nav.portal':   'Partner Portal',
      'ifood.nav.editing':  'Order Editing',
      'ifood.nav.logistics':'Logistics',
      'ifood.nav.origin':   'Origin',
      'ifood.s1.chip':   'Senior PM · Partner Portal · 2022',
      'ifood.s1.title':  'Partner Portal:<br>Performance Experience',
      'ifood.s1.body1':  'The Partner Portal is the B2B platform where more than <strong>350k restaurants</strong> manage their business within iFood. The underlying tension was clear: many owners felt they were <strong>forced to be on iFood</strong>, without seeing the value the platform could generate for them. On top of that, they had no benchmark — they didn\'t know whether they were performing well or not, or what to do to change it.',
      'ifood.s1.body2':  'The squad\'s goal was to turn performance data into <strong>clear, actionable, and free information</strong> — reinforcing the perception of partnership, not dependency.',
      'ifood.s1.disc.label': 'How we got to the solution',
      'ifood.jt1.label': 'Daily stakeholder immersion',
      'ifood.jt1.sub':   'Near-daily contact with business areas to understand expectations and what the product needed to be for them',
      'ifood.jt2.label': 'Qual & quant research with restaurants',
      'ifood.jt2.sub':   'Individual interviews and group workshops in the partner forum to understand what blocked data comprehension',
      'ifood.jt3.label': 'Feasibility with the data team',
      'ifood.jt3.sub':   'Ongoing alignment with analytics to map which data existed, what was reliable, and what could be surfaced',
      'ifood.s1.built.label': 'What was built',
      'ifood.f1.title': 'Metrics dashboard',       'ifood.f1.desc': 'Sales, orders, and average ticket in one place',
      'ifood.f2.title': 'Benchmark with peers',    'ifood.f2.desc': 'Comparison with restaurants in the same category and region',
      'ifood.f3.title': 'Action recommendations',  'ifood.f3.desc': 'Concrete steps to improve performance',
      'ifood.f4.title': 'Customer map',            'ifood.f4.desc': 'Geographic view of where the restaurant\'s customers are',
      'ifood.f5.title': 'Top-selling items',        'ifood.f5.desc': 'Which dishes sell most and on which days of the week',
      'ifood.f6.title': 'Explanatory tooltips',     'ifood.f6.desc': 'Accessible language for owners with lower data literacy',
      'ifood.s1.insight.label': 'The central discovery',
      'ifood.s1.insight.text':  'The main obstacle wasn\'t a lack of data — it was <strong>language</strong>. Restaurant owners didn\'t understand technical terms. Replacing jargon with everyday words, contextualizing numbers with benchmarks, and adding explanatory tooltips was what moved the CSAT needle.',
      'ifood.csat.title': 'CSAT in 5 months',
      'ifood.csat.desc':  'Qualitative research, short iteration cycles, and accessible language as the primary lever.',
      'ifood.quote.body':   'A dark kitchen restaurant reported that, upon seeing its customer location map for the first time, it realized it could relocate and significantly cut delivery costs — a strategic decision made possible by the data.',
      'ifood.quote.source': 'Qualitative feedback received after the customer map launch',
      'ifood.s2.chip':  'The product',
      'ifood.s2.body':  '<strong>iFood Shop</strong> is iFood\'s B2B marketplace — a platform where restaurants buy supplies, packaging, and products from suppliers directly within the iFood ecosystem. Over nearly 3 years, I worked across the product\'s main levers: from logistics to a full checkout refactor.',
      'ifood.s2.link':  'Access iFood Shop →',
      'ifood.s3.chip':   'Senior PM · iFood Shop · 2022 – 2024',
      'ifood.s3.title':  'Cart & Checkout Refactor',
      'ifood.s3.body':   'iFood Shop inherited the cart from the iFood consumer app — which works well for ordering pizza, but not for B2B behavior. <strong>Restaurants browse, compare prices across suppliers, and build their cart gradually.</strong> The funnel showed this mismatch was costing heavily in conversion.',
      'ifood.s3.diag.label': 'The diagnosis · before the refactor',
      'ifood.s3.m1.label': 'conversion in app<br><em style="font-style:normal;color:var(--muted-soft);">vs. 15% on web</em>',
      'ifood.s3.m2.label': 'cart abandonment<br>in app',
      'ifood.s3.m3.label': 'cart abandonment<br>on web',
      'ifood.s3.res.label': 'What the research revealed',
      'ifood.jt4.label': 'Cart that cleared',
      'ifood.jt4.sub':   'Switching suppliers wiped all items — consumer app behavior that makes no sense in B2B',
      'ifood.jt5.label': 'Bugs blocking the flow',
      'ifood.jt5.sub':   'Keyboard that popped up and wouldn\'t close, trapping the user mid-journey',
      'ifood.jt6.label': 'Steps in the wrong order',
      'ifood.jt6.sub':   'Payment came before delivery — but shipping changes the final price, forcing users to go back and revise',
      'ifood.s3.built.label': 'What was built',
      'ifood.g1.title': 'Multi-seller cart',                        'ifood.g1.desc': 'Restaurants add items from multiple suppliers and check out one order at a time',
      'ifood.g2.title': 'Inverted flow: delivery → payment',         'ifood.g2.desc': 'Users see the final price including shipping before choosing a payment method',
      'ifood.g3.title': 'Cart redesign',                            'ifood.g3.desc': 'New visual hierarchy, clear order summary, and revised information architecture',
      'ifood.g4.title': 'Bug fixes and error feedback',              'ifood.g4.desc': 'Elimination of flow-breaking errors and improved error messaging',
      'ifood.r1.delta': '↑ 9 percentage points', 'ifood.r1.label': 'cart conversion',
      'ifood.r2.delta': '↑ 12 percentage points','ifood.r2.label': 'total app conversion',
      'ifood.r3.delta': 'GMV 2.5×',              'ifood.r3.label': 'from 400k → 1 million in GMV',
      'ifood.s4.chip':  'Mid-level PM · iFood Shop · 2022',
      'ifood.s4.title': 'Order Editing & Stockout',
      'ifood.s4.body':  'In the Supplier Admin squad, the focus was on giving <strong>operational autonomy to Shop suppliers</strong>. Before this feature, any adjustment to an order — missing item, wrong quantity, or cancellation — required the supplier to contact iFood support, which then manually reached out to the purchasing restaurant.',
      'ifood.before.label': 'Before the feature',
      'ifood.before.step1': 'Supplier detects issue',
      'ifood.before.step2': 'Calls / emails support',
      'ifood.before.step3': 'Support contacts restaurant',
      'ifood.before.step4': 'Manual refund',
      'ifood.before.note':  'Slow process, dependent on third parties, and a major source of support tickets.',
      'ifood.node1.tag':   'What changed',
      'ifood.node1.title': 'Supplier edits the order directly in the platform',
      'ifood.node1.sub':   'Three types of editing available',
      'ifood.jt7.label': 'Full stockout',          'ifood.jt7.sub': 'Item completely unavailable in inventory',
      'ifood.jt8.label': 'Quantity reduction',     'ifood.jt8.sub': 'Ordered 10, only 6 available — partial adjustment',
      'ifood.jt9.label': 'Full cancellation',      'ifood.jt9.sub': 'Entire order unavailable for delivery',
      'ifood.node2.tag':   'Automatic processing',
      'ifood.node2.title': 'System calculates and processes refund by payment method',
      'ifood.node2.sub':   'Specific logic for each method — no manual intervention',
      'ifood.pay1.method': 'Credit card',  'ifood.pay1.action': 'New pre-authorization generated in the same session',
      'ifood.pay2.method': 'PIX',          'ifood.pay2.action': 'Instant refund to the originating key',
      'ifood.pay3.method': 'Boleto',       'ifood.pay3.action': 'New boleto issued with adjusted amount',
      'ifood.out1': '<span class="material-symbols-outlined">notifications</span> <span>Restaurant automatically notified</span>',
      'ifood.out2': '<span class="material-symbols-outlined">notifications_off</span> <span>Support out of the loop</span>',
      'ifood.out3': '<span class="material-symbols-outlined">trending_down</span> <span>Support tickets reduced</span>',
      'ifood.s4.insight.text': 'Support was completely removed from the loop. Suppliers began resolving issues autonomously, refunds were automated by payment method, and order-related support tickets dropped significantly — with no manual intervention needed.',
      'ifood.s5.chip':  'Junior PM · iFood Shop · 2021 – 2022',
      'ifood.s5.title': 'Logistics & Post-Sale',
      'ifood.s5.body':  'My first PM role was in the iFood Shop post-sale and logistics squad. The central challenge was <strong>expanding the supplier base without owning a fleet</strong> and improving the end-to-end delivery experience. Three main fronts:',
      'ifood.i1.title': 'Logistics as a Service (LaaS)', 'ifood.i1.desc': 'Integration of third-party carriers into the Shop ecosystem, opening doors for suppliers without their own fleet. Scalable and replicable solution for the marketplace.',
      'ifood.i1.link': 'See publication →',
      'ifood.i2.title': 'Delivery Scheduling',            'ifood.i2.desc': 'Feature allowing restaurants to plan incoming deliveries in advance — fewer operational surprises and more control over inventory flow.',
      'ifood.i3.title': 'Communication Flow',             'ifood.i3.desc': 'Structured post-purchase communication flow via <strong>email and WhatsApp</strong>, keeping suppliers and buyers aligned throughout the entire delivery journey.',
      'ifood.s5.insight.text': 'LaaS integration opened the marketplace to suppliers without their own fleet, directly growing the available partner base. Delivery scheduling and the post-purchase communication flow reduced operational friction — improving the experience for restaurants and suppliers throughout the journey.',
      'ifood.s6.chip':  'Origin · 2020 – 2021',
      'ifood.s6.title': 'Where it all started',
      'ifood.s6.body':  'I joined iFood as a <strong>Software Engineer</strong> through the <strong>Mobile Dream</strong> program — an initiative to hire and develop junior analysts. I worked on the backend of the Partner Portal, in the Menu product. That experience was the starting point: deeply understanding how the product worked from the inside gave me the foundation for the internal transition to Product Management.',
      'ifood.nav.prev': '← Grupo Boticário',
      'ifood.nav.next': 'Engineering & Research →',

      /* ── Boticário ── */
      'bot.page.title':  'Staff Product Manager',
      'bot.page.period': 'September 2024 – April 2026 · 1 year 8 months',
      'bot.nav.sellout': 'Sellout Forecasting',
      'bot.nav.results': 'Results',
      'bot.s1.chip':  'The Product',
      'bot.s1.title': 'GDEM — Demand Management',
      'bot.s1.body':  'GDEM is Grupo Boticário\'s internal demand planning tool. Using statistical models, it helps planners forecast SKU demand — and this forecast goes directly to Supply to guide manufacturing. There\'s no room for error: <strong>a wrong forecast means stockouts on franchise shelves.</strong>',
      'bot.s1.problem.label': 'Context & scale',
      'bot.s1.m1.label': 'SKUs planned — Boticário<br>and Eudora brands',
      'bot.s1.m2.label': 'planners responsible for<br>all this volume',
      'bot.s1.m3.label': 'margin for error — wrong forecast<br>goes directly to Supply',
      'bot.s1.did.label': 'What I did',
      'bot.jt1.label': 'Pain discovery',     'bot.jt1.sub': 'Interviews with planners to understand what stalled the process and where the model failed',
      'bot.jt2.label': 'Data-driven refinement','bot.jt2.sub': 'Backlog prioritized together with the Data Science team, with clear impact and feasibility criteria',
      'bot.jt3.label': 'Success metrics',     'bot.jt3.sub': 'Defined accuracy KPIs (WAPE) and planning cycle time as north stars for the squad',
      'bot.s2.chip':  'Front 1 · B2B Discovery',
      'bot.s2.title': 'Expanding GDEM<br>to the B2B channel',
      'bot.s2.body':  'GDEM was built for the company\'s standard process — but the B2B channel operates with its own dynamics that the product couldn\'t support. The B2B team felt GDEM simply <strong>"didn\'t work for them"</strong>. The GDEM team, in turn, didn\'t understand how B2B operated. Without mutual understanding, any solution would be a shot in the dark.',
      'bot.s2.areas.label': '5 areas mapped in the assessment',
      'bot.a1.title': 'B2B Demand Planners', 'bot.a1.desc': 'Direct GDEM users in the B2B channel',
      'bot.a2.title': 'B2B Demand Managers', 'bot.a2.desc': 'Stakeholders with strategic channel vision',
      'bot.a3.title': 'Commercial Planning',  'bot.a3.desc': 'Area connecting demand to commercial targets',
      'bot.a4.title': 'Control Tower',        'bot.a4.desc': 'Operational and monitoring view',
      'bot.a5.title': 'Data',                'bot.a5.desc': 'Technical team responsible for models and infrastructure',
      'bot.s2.insight1.label': 'The central discovery',
      'bot.s2.insight1.text':  'The gap wasn\'t technical — it was conceptual. B2B had a fundamentally different demand process from the standard channel, and neither side understood the other well. The main output of the assessment was creating a shared language between the two worlds and, from there, scoping a viable MVP.',
      'bot.s2.del.label': 'What was delivered',
      'bot.jt4.label': 'Full mapping',      'bot.jt4.sub': 'B2B demand process documented end-to-end, with feasibility data',
      'bot.jt5.label': '5-area alignment',   'bot.jt5.sub': 'Bi-weekly reviews until all parties reached a common understanding',
      'bot.jt6.label': 'MVP defined',        'bot.jt6.sub': 'Epics and stories broken down, feasibility mapped — ready for development',
      'bot.s2.insight2.text': 'After 10 stakeholder interviews across 5 areas and 4 bi-weekly reviews, the discovery landed on a well-defined MVP — and leadership approved the scope to move into development. The subsequent decision to deprioritize was a business call, not a lack of clarity: the product was ready to build, but other initiatives took precedence. <strong>A discovery that generates an informed decision is a discovery well done.</strong>',
      'bot.s3.chip':  'Front 2 · Sellout PM',
      'bot.s3.title': 'Sales Forecasting<br>for Consumers',
      'bot.s3.body':  'As PM for the Sellout Forecasting squad, the biggest problem when I joined wasn\'t a missing feature — it was a <strong>flood of incorrect data incidents</strong>. For 15 planners with a heavy operational load, a wrong data point meant submitting an incorrect forecast directly to Supply. There was no room for error.',
      'bot.s3.diag.label': 'The diagnosis',
      'bot.s3.diag.text':  'Business rules had been poorly aligned between business and tech during development. What was coded diverged from what stakeholders expected — the calculations produced different results than anticipated. It wasn\'t any single team\'s fault, but it needed to be fixed.',
      'bot.s3.did.label': 'What was done',
      'bot.jt7.label': 'Rule-by-rule mapping',    'bot.jt7.sub': 'Sat with key people in the demand area and documented each calculation logic — case by case, model by model',
      'bot.jt8.label': 'Validation against the code','bot.jt8.sub': 'Compared what was implemented against what was mapped, identifying where calculations diverged from expectations',
      'bot.jt9.label': 'Prioritization and visibility','bot.jt9.sub': 'Organized the inconsistencies found, prioritized fixes, and gave clear visibility to the business team',
      'bot.s3.result.label': 'Result',
      'bot.s3.stat.label': 'data incidents',
      'bot.s3.stat.desc':  'The systematic mapping of business rules turned a chronic quality problem into a reliable validation process.',
      'bot.s3.decision.label': 'A priority decision',
      'bot.s3.decision.text':  'During the expansion to the Eudora brand — with a set deadline — the business team urgently raised a performance issue across multiple simultaneous schedules and asked to halt everything. Instead of giving in to the pressure, I sat with key people and asked the right questions: <em>how many incidents were opened because of this? What caused it? Does it make sense to delay the expansion to fix this now?</em> The answer: no incidents, a one-off cause, average scenario — not critical. Together, we concluded the expansion was the priority. The performance issue was resolved shortly after.',
      'bot.s3.other.label': 'Other squad responsibilities',
      'bot.h1.title': 'Accuracy (WAPE)',             'bot.h1.desc': 'Continuous monitoring of forecast accuracy generated by the data model',
      'bot.h2.title': 'Planner experience',          'bot.h2.desc': 'UX within GDEM — the system began consolidating data previously scattered across multiple spreadsheets and databases',
      'bot.h3.title': 'Simplified C-curve',          'bot.h3.desc': 'Low-impact products stopped going through the complex process — the statistical model\'s output was trusted directly',
      'bot.h4.title': 'Data Science interface',      'bot.h4.desc': 'Integration of the model into the product and validation of outputs with the data team',
      'bot.s4.chip':  'Results · GDEM',
      'bot.s4.title': 'Impact on company<br>planning',
      'bot.r1.delta': '↓ 50% in cycle', 'bot.r1.label': 'planning cycle<br><em style="font-style:normal;color:var(--muted-soft);">was: 40 days</em>',
      'bot.r2.delta': 'forecast accuracy', 'bot.r2.label': 'demand forecast<br>accuracy',
      'bot.r3.delta': '↓ data incidents',  'bot.r3.label': 'incident reduction<br>in the Sellout squad',
      'bot.nav.prev': '← levva @ B3',
      'bot.nav.next': 'iFood →',

      /* ── Early Career ── */
      'early.page.title':  'Software Engineering & Research',
      'early.page.period': '2015 – 2020 · 5 years · The technical foundation that sets me apart',
      'early.s1.title': 'Why this matters',
      'early.s1.intro': 'Before becoming a PM, I was a software engineer. That path isn\'t just a resume detail — it\'s what sets me apart. I understand what engineering teams face, I can read code, participate in architecture decisions, and communicate requirements with precision. This foundation was built at <strong>Cogna Educação</strong> and <strong>CNPq</strong>, before joining iFood.',
      'early.s2.title': 'Cogna Educação · Exam Platform · 2018 – Dec 2019',
      'early.provas.name': 'Exam Platform',
      'early.provas.sub':  'Portal for teachers to create and manage digital assessments',
      'early.provas.ctx':  'An internal system for <strong>teachers</strong> in the Kroton / Cogna ecosystem: a portal where they could register questions, build assessments, and track student performance by class. I worked on developing and evolving the platform as a Software Developer, centralizing the assessment flow — from question authoring to digital delivery.',
      'early.stack.label': 'Stack used',
      'early.s3.title': 'Cogna Educação · Trilha do Enem · Jan 2017 – Dec 2017',
      'early.enem.name': 'Trilha do Enem',
      'early.enem.sub':  'Free adaptive prep platform for Brazil\'s national university entrance exam (ENEM)',
      'early.enem.stat': 'students reached',
      'early.enem.link1': 'How to study for ENEM for free',
      'early.enem.link2': 'What it is and how it works',
      'early.enem.link3': 'Official channel',
      'early.enem.ctx':  'I joined Cogna as an intern and was hired full-time as a Developer. I worked on building and evolving <strong>Trilha do Enem</strong>, a free platform offering classes, mock exams, and an adaptive study plan for students across Brazil. The platform was covered by the press and reached more than <strong>250k users</strong>.',
      'early.s4.title': 'AceleraDev Java Women · Codenation + QuintoAndar · 2019',
      'early.acelera.name': 'AceleraDev Java Women',
      'early.acelera.sub':  'Exclusive program for women in Back-end Java',
      'early.acelera.stat': 'women selected<br>from nearly 2,000 applicants',
      'early.acelera.ctx':  'In late 2019, I was selected for <strong>AceleraDev Java Women</strong> — a free program exclusively for women, created by Codenation in partnership with <strong>QuintoAndar</strong>. Ten weeks of immersion in Back-end development with Java, with in-person classes at QuintoAndar\'s São Paulo office and weekly coding challenges. Of the 30 selected participants, QuintoAndar directly hired 11 at the end of the program.',
      'early.s5.title': 'CNPq · Scientific Initiation · Dec 2015 – Dec 2016',
      'early.cnpq.name': 'FXCode — Icon Recognition',
      'early.cnpq.sub':  'Research in convolutional neural networks applied to image recognition',
      'early.cnpq.stat': 'app platforms where the model was deployed',
      'early.cnpq.ctx':  'As a <strong>CNPq</strong> research fellow, I conducted scientific initiation research in image recognition using <strong>convolutional neural networks</strong>. In the <strong>FXCode</strong> project, I was responsible for producing a model capable of recognizing icons — trained in Python with the Keras library — and integrating it into a mobile app for Android and iOS.',
      'early.nav.prev': '← iFood',
      'early.nav.next': 'levva @ B3 →',
    }
  };

  function applyLang(lang) {
    var l = T[lang] || T['pt'];

    document.querySelectorAll('[data-i18n]').forEach(function (el) {
      var key = el.getAttribute('data-i18n');
      if (l[key] !== undefined) el.textContent = l[key];
    });

    document.querySelectorAll('[data-i18n-html]').forEach(function (el) {
      var key = el.getAttribute('data-i18n-html');
      if (l[key] !== undefined) el.innerHTML = l[key];
    });

    document.documentElement.lang = lang === 'en' ? 'en' : 'pt-BR';
    localStorage.setItem('lang', lang);

    document.querySelectorAll('.lang-toggle').forEach(function (btn) {
      btn.setAttribute('data-active', lang);
    });
  }

  window.applyLang = applyLang;
  window.getLangTranslations = function () { return T; };

  document.addEventListener('DOMContentLoaded', function () {
    var saved = localStorage.getItem('lang') || 'pt';
    applyLang(saved);
  });

})();
